# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21b3edbeb550c3f66a43728a50d8c7e3e119922eb01aa658f51fee3a86edf9c3d66586990ddd40beb933dd09ff2a7e70cfe40acc552c9ece81c10b8a07b02dff

test:
  secret_key_base: 66cf506d8713a63315f0cfd0d04fac12c6f07ccac825277708687dde3bf6aee0ae917f719094c6de1e6eb53de93a0363d75a248befc02578e73be68c02df6856

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
